name: Dispatcher
on:
  push:
    branches: [ci/dispatcher]

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["barbinbrad/fiber"]
    timeout-minutes: 5
    steps:
      - name: Dispatch to fiber
        run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
          --request POST \
          --data '{"event_type": "release", "client_payload": { "key": ${{ secrets.DISPATCH_KEY_PROD }} }}' https://api.github.com/repos/${{ matrix.repo }}/dispatches
